DROP TABLE EMPLOYEES;
DROP TABLE CUSTOMERS;
DROP TABLE ZIPCODES;

CREATE TABLE ZIPCODES
(
    ZIP NUMBER(5) PRIMARY KEY,
    CITY VARCHAR2(20)
);

CREATE TABLE CUSTOMERS
(
    CNO NUMBER PRIMARY KEY,
    CNAME VARCHAR2(20),
    STREET VARCHAR2(100),
    ZIP NUMBER(5),
    PHONE VARCHAR2(12),
    CONSTRAINT fk_zip_customers
        FOREIGN KEY (ZIP)
        REFERENCES ZIPCODES(ZIP)
);

CREATE TABLE EMPLOYEES
(
    ENO NUMBER PRIMARY KEY,
    ENAME VARCHAR2(30),
    ZIP NUMBER(5),
    HDATE DATE,
    CONSTRAINT fk_zip_employees
        FOREIGN KEY (ZIP)
        REFERENCES ZIPCODES(ZIP)
);